apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: ingress-port-5090
spec:
  endpointSelector:
    matchLabels:
      network-policy/ingress-port: "5090"
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "5090"
              protocol: TCP
