apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-api-configmap
  namespace: too-restful-api
data:
  test-list-data.json: |
    [{
        "alive" : "true"
    }]

  dotnet-version.json: |
    {
      "releases": [
        {
          "version" : "8.0"
        },
        {
          "version" : "9.0"
        },
        {
          "version" : "10.0"
        }
      ]
    }
