apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: ingess-nginx-port-5090
spec:
  endpointSelector:
    matchLabels:
      network-policy/ingress-nginx-port: "5090"
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: ingress-nginx
      toPorts:
        - ports:
            - port: "5090"
